service: s3-ensure-versioning-enabled
provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetBucketVersioning"
        - "s3:PutBucketVersioning"
      Resource: "arn:aws:s3:::*"
functions:
  S3VersioningEnforcer:
    handler: index.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.s3"
            detail-type:
              - "AWS API Call via CloudTrail"
            detail:
              eventSource:
                - "s3.amazonaws.com"
              eventName:
                - "CreateBucket"
